apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
  labels:
    app: springboot
  
    tier: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
      tier: dev

  template:
    metadata:
      name: springboot
      labels:
        app: springboot
        tier: dev
    spec:
      containers:
        - name: springbootapp
          image: 9902736822/springbootapp:v3.0.0
          ports:
          - containerPort: 8080
          volumeMounts:
          - mountPath: /etc/hosts
            name: hostsmount
      volumes:
        - name: hostsmount
          hostPath:
            path: /etc/hosts
